query ShowList {
  genres(delay: 2000) @loading {
    edges @loading(count: 10) {
      node @loading {
        name @loading
        shows @loading {
          edges @loading(count: 5) {
            node @loading {
              id
              name
              billboard {
                source
              }
            }
          }
        }
      }
    }
  }
}
